// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPpieYMKwYxLKmtHVQSoUUqkOkKue5tM',
    appId: '1:389900334765:web:c29bdb7aa90575bbbe3824',
    messagingSenderId: '389900334765',
    projectId: 'chat-app-f22bf',
    authDomain: 'chat-app-f22bf.firebaseapp.com',
    storageBucket: 'chat-app-f22bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFcg9GtuEbT0Yjb-G5J_wVeeg1RHBqlw',
    appId: '1:389900334765:android:d799a0c171344b05be3824',
    messagingSenderId: '389900334765',
    projectId: 'chat-app-f22bf',
    storageBucket: 'chat-app-f22bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMGP645wBa071OHj5VKmcjcSSoirfvJW0',
    appId: '1:389900334765:ios:2f4cbda61672d471be3824',
    messagingSenderId: '389900334765',
    projectId: 'chat-app-f22bf',
    storageBucket: 'chat-app-f22bf.appspot.com',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMGP645wBa071OHj5VKmcjcSSoirfvJW0',
    appId: '1:389900334765:ios:2f4cbda61672d471be3824',
    messagingSenderId: '389900334765',
    projectId: 'chat-app-f22bf',
    storageBucket: 'chat-app-f22bf.appspot.com',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnPpieYMKwYxLKmtHVQSoUUqkOkKue5tM',
    appId: '1:389900334765:web:6f7c04befb3f6e53be3824',
    messagingSenderId: '389900334765',
    projectId: 'chat-app-f22bf',
    authDomain: 'chat-app-f22bf.firebaseapp.com',
    storageBucket: 'chat-app-f22bf.appspot.com',
  );
}
